//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Nikitin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ReaderBook = new HashSet<ReaderBook>();
        }
    
        public int Id { get; set; }
        public string TitleBook { get; set; }
        public int IdAuthor { get; set; }
        public int IdPublishingHouse { get; set; }
        public System.DateTime YearOfPublication { get; set; }
        public int NumberOfPages { get; set; }
        public int IdGenre { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReaderBook> ReaderBook { get; set; }
    }
}
